# Open payments dataset analysis
# Diabetes and Endocrinology

# Import package

## import package

In [ ]:
import pandas as pd
import os
import glob
import sys


pd.options.display.max_columns = 100

## Mount Google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Declare path to import and save payment dataset

In [ ]:
path_out1 = "path for general payments/"
path_out2 = "path for research payments/"
path_out3 = "path for ownership payments/"
path_out_profile = "path for profile data/"

In [ ]:
path_out_stata = "path for dataset for stata analysis"

In [ ]:
specialty = "207RE0101X"

# NPI database extraction

## NPI dataset

In [ ]:
usecols = ['NPI', 'Entity Type Code', 'Replacement NPI', 
           'Provider Organization Name (Legal Business Name)', 'Provider Last Name (Legal Name)', 
           'Provider First Name', 'Provider Middle Name', 
           'Provider Other Organization Name', 'Provider Other Organization Name Type Code', 
           'Provider Other Last Name', 'Provider Other First Name', 
           'Provider Other Middle Name',  'Provider Business Practice Location Address City Name', 
           'Provider Business Practice Location Address State Name', 'Provider Enumeration Date', 
           'Last Update Date', 'NPI Deactivation Reason Code', 'NPI Deactivation Date', 
           'NPI Reactivation Date', 'Provider Gender Code', 'Authorized Official Title or Position', 
           'Healthcare Provider Taxonomy Code_1', 'Healthcare Provider Primary Taxonomy Switch_1', 
           'Healthcare Provider Taxonomy Code_2', 'Healthcare Provider Primary Taxonomy Switch_2', 
           'Healthcare Provider Taxonomy Code_3', 'Healthcare Provider Primary Taxonomy Switch_3', 
           'Healthcare Provider Taxonomy Code_4', 'Healthcare Provider Primary Taxonomy Switch_4', 
           'Healthcare Provider Taxonomy Code_5', 'Healthcare Provider Primary Taxonomy Switch_5', 
           'Healthcare Provider Taxonomy Code_6', 'Healthcare Provider Primary Taxonomy Switch_6', 
           'Healthcare Provider Taxonomy Code_7', 'Healthcare Provider Primary Taxonomy Switch_7', 
           'Healthcare Provider Taxonomy Code_8', 'Healthcare Provider Primary Taxonomy Switch_8', 
           'Healthcare Provider Taxonomy Code_9', 'Healthcare Provider Primary Taxonomy Switch_9', 
           'Healthcare Provider Taxonomy Code_10', 'Healthcare Provider Primary Taxonomy Switch_10',
           'Healthcare Provider Taxonomy Code_11', 'Healthcare Provider Primary Taxonomy Switch_11',
           'Healthcare Provider Taxonomy Code_12', 'Healthcare Provider Primary Taxonomy Switch_12',
           'Healthcare Provider Taxonomy Code_13', 'Healthcare Provider Primary Taxonomy Switch_13',
           'Healthcare Provider Taxonomy Code_14', 'Healthcare Provider Primary Taxonomy Switch_14',
           'Healthcare Provider Taxonomy Code_15', 'Healthcare Provider Primary Taxonomy Switch_15', 
           'Certification Date' ]

In [ ]:
npi = pd.read_csv("/content/drive/MyDrive/national provider identifier file/npidata_pfile_20050523-20220710.csv", 
                   chunksize= 1000000, usecols= usecols, low_memory=False,
                  keep_default_na= "0")

In [ ]:
npi = pd.concat((r for r in npi), ignore_index=True)

In [ ]:
npi = npi[npi["Entity Type Code"] == 1]

In [ ]:
npi_specialty = npi[((npi["Healthcare Provider Primary Taxonomy Switch_1"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_1"] == specialty)) |
                   ((npi["Healthcare Provider Primary Taxonomy Switch_2"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_2"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_3"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_3"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_4"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_4"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_5"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_5"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_6"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_6"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_7"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_7"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_8"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_8"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_9"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_9"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_10"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_10"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_11"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_11"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_12"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_12"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_13"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_13"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_14"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_14"] == specialty)) |
                    ((npi["Healthcare Provider Primary Taxonomy Switch_15"] == "Y" ) & (npi["Healthcare Provider Taxonomy Code_15"] == specialty)) ]
del npi

In [ ]:
npi_specialty

,NPI,Entity Type Code,Replacement NPI,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Other Organization Name,Provider Other Organization Name Type Code,Provider Other Last Name,Provider Other First Name,Provider Other Middle Name,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Enumeration Date,Last Update Date,NPI Deactivation Reason Code,NPI Deactivation Date,NPI Reactivation Date,Provider Gender Code,Authorized Official Title or Position,Healthcare Provider Taxonomy Code_1,Healthcare Provider Primary Taxonomy Switch_1,Healthcare Provider Taxonomy Code_2,Healthcare Provider Primary Taxonomy Switch_2,Healthcare Provider Taxonomy Code_3,Healthcare Provider Primary Taxonomy Switch_3,Healthcare Provider Taxonomy Code_4,Healthcare Provider Primary Taxonomy Switch_4,Healthcare Provider Taxonomy Code_5,Healthcare Provider Primary Taxonomy Switch_5,Healthcare Provider Taxonomy Code_6,Healthcare Provider Primary Taxonomy Switch_6,Healthcare Provider Taxonomy Code_7,Healthcare Provider Primary Taxonomy Switch_7,Healthcare Provider Taxonomy Code_8,Healthcare Provider Primary Taxonomy Switch_8,Healthcare Provider Taxonomy Code_9,Healthcare Provider Primary Taxonomy Switch_9,Healthcare Provider Taxonomy Code_10,Healthcare Provider Primary Taxonomy Switch_10,Healthcare Provider Taxonomy Code_11,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Taxonomy Code_12,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Taxonomy Code_13,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Taxonomy Code_14,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Taxonomy Code_15,Healthcare Provider Primary Taxonomy Switch_15,Certification Date
85,1740283779,1.0,NaN,NaN,JAVIER,EMMANUEL,NaN,NaN,NaN,NaN,NaN,NaN,HARTFORD,CT,05/23/2005,02/07/2014,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
130,1316940463,1.0,NaN,NaN,DIEZ,JORGE,L.,NaN,NaN,NaN,NaN,NaN,EAST HARTFORD,CT,05/23/2005,06/18/2021,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/18/2021
344,1659374676,1.0,NaN,NaN,PERKINS,VICTORIA,ANNE,NaN,NaN,NaN,NaN,NaN,GREENVILLE,NC,05/23/2005,09/14/2015,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
658,1942203930,1.0,NaN,NaN,SOTOUDEH,FARANAK,FOROOZANFAR,NaN,NaN,NaN,NaN,NaN,GREENBELT,MD,05/23/2005,10/03/2016,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
822,1457354581,1.0,NaN,NaN,CAVALE,ARVIND,RAMACHANDRARAO,NaN,NaN,NaN,NaN,NaN,FEASTERVILLE TREVOSE,PA,05/23/2005,11/09/2012,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7230783,1861141657,1.0,NaN,NaN,CHURCHILL,JESSIE,NaN,NaN,NaN,NaN,NaN,NaN,NOVATO,CA,03/21/2022,06/17/2022,NaN,NaN,NaN,F,NaN,163W00000X,N,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/17/2022
7272235,1528700523,1.0,NaN,NaN,DAVIS,AMALA,NaN,NaN,NaN,NaN,NaN,NaN,BRONX,NY,04/11/2022,07/07/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/07/2022
7286104,1679216519,1.0,NaN,NaN,LAND,ANICA,PEROS,NaN,NaN,NaN,NaN,NaN,DURHAM,NC,04/19/2022,04/19/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/19/2022
7328551,1043958036,1.0,NaN,NaN,LEE,SHARON,NaN,NaN,NaN,NaN,NaN,NaN,CINCINNATI,OH,05/20/2022,05/20/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/20/2022
7354681,1215666862,1.0,NaN,NaN,GANGULY,SONALI,NaN,NaN,NaN,LAHIRY,SONALI,NaN,SUWANEE,GA,06/08/2022,07/08/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/08/2022

In [ ]:
npi_specialty   
list_npi = list(npi_specialty["NPI"])

In [ ]:
npi_specialty["month"] = npi_specialty["Provider Enumeration Date"].str[:2].astype(int)
npi_specialty["day"] = npi_specialty["Provider Enumeration Date"].str.slice(start=3, stop=5).astype(int)
npi_specialty["year"] = npi_specialty["Provider Enumeration Date"].str.slice(start=6, stop=10).astype(int)
npi_specialty

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,NPI,Entity Type Code,Replacement NPI,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Other Organization Name,Provider Other Organization Name Type Code,Provider Other Last Name,Provider Other First Name,Provider Other Middle Name,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Enumeration Date,Last Update Date,NPI Deactivation Reason Code,NPI Deactivation Date,NPI Reactivation Date,Provider Gender Code,Authorized Official Title or Position,Healthcare Provider Taxonomy Code_1,Healthcare Provider Primary Taxonomy Switch_1,Healthcare Provider Taxonomy Code_2,Healthcare Provider Primary Taxonomy Switch_2,Healthcare Provider Taxonomy Code_3,Healthcare Provider Primary Taxonomy Switch_3,Healthcare Provider Taxonomy Code_4,Healthcare Provider Primary Taxonomy Switch_4,Healthcare Provider Taxonomy Code_5,Healthcare Provider Primary Taxonomy Switch_5,Healthcare Provider Taxonomy Code_6,Healthcare Provider Primary Taxonomy Switch_6,Healthcare Provider Taxonomy Code_7,Healthcare Provider Primary Taxonomy Switch_7,Healthcare Provider Taxonomy Code_8,Healthcare Provider Primary Taxonomy Switch_8,Healthcare Provider Taxonomy Code_9,Healthcare Provider Primary Taxonomy Switch_9,Healthcare Provider Taxonomy Code_10,Healthcare Provider Primary Taxonomy Switch_10,Healthcare Provider Taxonomy Code_11,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Taxonomy Code_12,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Taxonomy Code_13,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Taxonomy Code_14,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Taxonomy Code_15,Healthcare Provider Primary Taxonomy Switch_15,Certification Date,month,day,year
85,1740283779,1.0,NaN,NaN,JAVIER,EMMANUEL,NaN,NaN,NaN,NaN,NaN,NaN,HARTFORD,CT,05/23/2005,02/07/2014,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,2005
130,1316940463,1.0,NaN,NaN,DIEZ,JORGE,L.,NaN,NaN,NaN,NaN,NaN,EAST HARTFORD,CT,05/23/2005,06/18/2021,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/18/2021,5,23,2005
344,1659374676,1.0,NaN,NaN,PERKINS,VICTORIA,ANNE,NaN,NaN,NaN,NaN,NaN,GREENVILLE,NC,05/23/2005,09/14/2015,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,2005
658,1942203930,1.0,NaN,NaN,SOTOUDEH,FARANAK,FOROOZANFAR,NaN,NaN,NaN,NaN,NaN,GREENBELT,MD,05/23/2005,10/03/2016,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,2005
822,1457354581,1.0,NaN,NaN,CAVALE,ARVIND,RAMACHANDRARAO,NaN,NaN,NaN,NaN,NaN,FEASTERVILLE TREVOSE,PA,05/23/2005,11/09/2012,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,2005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7230783,1861141657,1.0,NaN,NaN,CHURCHILL,JESSIE,NaN,NaN,NaN,NaN,NaN,NaN,NOVATO,CA,03/21/2022,06/17/2022,NaN,NaN,NaN,F,NaN,163W00000X,N,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/17/2022,3,21,2022
7272235,1528700523,1.0,NaN,NaN,DAVIS,AMALA,NaN,NaN,NaN,NaN,NaN,NaN,BRONX,NY,04/11/2022,07/07/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/07/2022,4,11,2022
7286104,1679216519,1.0,NaN,NaN,LAND,ANICA,PEROS,NaN,NaN,NaN,NaN,NaN,DURHAM,NC,04/19/2022,04/19/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/19/2022,4,19,2022
7328551,1043958036,1.0,NaN,NaN,LEE,SHARON,NaN,NaN,NaN,NaN,NaN,NaN,CINCINNATI,OH,05/20/2022,05/20/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/20/2022,5,20,2022
7354681,1215666862,1.0,NaN,NaN,GANGULY,SONALI,NaN,NaN,NaN,LAHIRY,SONALI,NaN,SUWANEE,GA,06/08/2022,07/08/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/08/2022,6,8,2022

In [ ]:
# define January 2000 as month 1
npi_specialty["cmonth"] = ((npi_specialty["year"]-2000)*12 + npi_specialty["month"])
npi_specialty

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,NPI,Entity Type Code,Replacement NPI,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Other Organization Name,Provider Other Organization Name Type Code,Provider Other Last Name,Provider Other First Name,Provider Other Middle Name,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Enumeration Date,Last Update Date,NPI Deactivation Reason Code,NPI Deactivation Date,NPI Reactivation Date,Provider Gender Code,Authorized Official Title or Position,Healthcare Provider Taxonomy Code_1,Healthcare Provider Primary Taxonomy Switch_1,Healthcare Provider Taxonomy Code_2,Healthcare Provider Primary Taxonomy Switch_2,Healthcare Provider Taxonomy Code_3,Healthcare Provider Primary Taxonomy Switch_3,Healthcare Provider Taxonomy Code_4,Healthcare Provider Primary Taxonomy Switch_4,Healthcare Provider Taxonomy Code_5,Healthcare Provider Primary Taxonomy Switch_5,Healthcare Provider Taxonomy Code_6,Healthcare Provider Primary Taxonomy Switch_6,Healthcare Provider Taxonomy Code_7,Healthcare Provider Primary Taxonomy Switch_7,Healthcare Provider Taxonomy Code_8,Healthcare Provider Primary Taxonomy Switch_8,Healthcare Provider Taxonomy Code_9,Healthcare Provider Primary Taxonomy Switch_9,Healthcare Provider Taxonomy Code_10,Healthcare Provider Primary Taxonomy Switch_10,Healthcare Provider Taxonomy Code_11,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Taxonomy Code_12,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Taxonomy Code_13,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Taxonomy Code_14,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Taxonomy Code_15,Healthcare Provider Primary Taxonomy Switch_15,Certification Date,month,day,year,cmonth
85,1740283779,1.0,NaN,NaN,JAVIER,EMMANUEL,NaN,NaN,NaN,NaN,NaN,NaN,HARTFORD,CT,05/23/2005,02/07/2014,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,2005,65
130,1316940463,1.0,NaN,NaN,DIEZ,JORGE,L.,NaN,NaN,NaN,NaN,NaN,EAST HARTFORD,CT,05/23/2005,06/18/2021,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/18/2021,5,23,2005,65
344,1659374676,1.0,NaN,NaN,PERKINS,VICTORIA,ANNE,NaN,NaN,NaN,NaN,NaN,GREENVILLE,NC,05/23/2005,09/14/2015,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,2005,65
658,1942203930,1.0,NaN,NaN,SOTOUDEH,FARANAK,FOROOZANFAR,NaN,NaN,NaN,NaN,NaN,GREENBELT,MD,05/23/2005,10/03/2016,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,2005,65
822,1457354581,1.0,NaN,NaN,CAVALE,ARVIND,RAMACHANDRARAO,NaN,NaN,NaN,NaN,NaN,FEASTERVILLE TREVOSE,PA,05/23/2005,11/09/2012,NaN,NaN,NaN,M,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5,23,2005,65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7230783,1861141657,1.0,NaN,NaN,CHURCHILL,JESSIE,NaN,NaN,NaN,NaN,NaN,NaN,NOVATO,CA,03/21/2022,06/17/2022,NaN,NaN,NaN,F,NaN,163W00000X,N,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/17/2022,3,21,2022,267
7272235,1528700523,1.0,NaN,NaN,DAVIS,AMALA,NaN,NaN,NaN,NaN,NaN,NaN,BRONX,NY,04/11/2022,07/07/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/07/2022,4,11,2022,268
7286104,1679216519,1.0,NaN,NaN,LAND,ANICA,PEROS,NaN,NaN,NaN,NaN,NaN,DURHAM,NC,04/19/2022,04/19/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,04/19/2022,4,19,2022,268
7328551,1043958036,1.0,NaN,NaN,LEE,SHARON,NaN,NaN,NaN,NaN,NaN,NaN,CINCINNATI,OH,05/20/2022,05/20/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,05/20/2022,5,20,2022,269
7354681,1215666862,1.0,NaN,NaN,GANGULY,SONALI,NaN,NaN,NaN,LAHIRY,SONALI,NaN,SUWANEE,GA,06/08/2022,07/08/2022,NaN,NaN,NaN,F,NaN,207RE0101X,Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,07/08/2022,6,8,2022,270

## Match NPI with OPD

In [ ]:
df_profile = pd.read_csv("/content/drive/MyDrive/OPD/OPD input/profile/data (22).csv", low_memory=False)

In [ ]:
df_profile['covered_recipient_npi'] = df_profile['covered_recipient_npi'].fillna(0)
df_profile['covered_recipient_npi'] = df_profile['covered_recipient_npi'].astype('int64')

In [ ]:
df_id = df_profile[df_profile["covered_recipient_npi"].isin(list_npi)] 
df_id

,covered_recipient_profile_type,covered_recipient_profile_id,covered_recipient_npi,covered_recipient_profile_first_name,covered_recipient_profile_middle_name,covered_recipient_profile_last_name,covered_recipient_profile_suffix,covered_recipient_profile_alternate_first_name1,covered_recipient_profile_alternate_middle_name1,covered_recipient_profile_alternate_last_name1,covered_recipient_profile_alternate_suffix1,covered_recipient_profile_address_line_1,covered_recipient_profile_address_line_2,covered_recipient_profile_city,covered_recipient_profile_state,covered_recipient_profile_zipcode,covered_recipient_profile_country_name,covered_recipient_profile_province_name,covered_recipient_profile_primary_specialty,covered_recipient_profile_license_state_code_1,covered_recipient_profile_license_state_code_2,covered_recipient_profile_license_state_code_3,covered_recipient_profile_license_state_code_4,covered_recipient_profile_license_state_code_5,covered_recipient_profile_alternate_first_name2,covered_recipient_profile_alternate_last_name2,covered_recipient_profile_alternate_first_name3,covered_recipient_profile_alternate_last_name3,covered_recipient_profile_alternate_first_name4,covered_recipient_profile_alternate_last_name4,covered_recipient_profile_alternate_first_name5,covered_recipient_profile_alternate_last_name5,has_multiple_ids
3,Covered Recipient Physician,4,1003024811,LISA,L,HAMAKER,NaN,NaN,NaN,NaN,NaN,100 MARKET ST STE 300,NaN,COLLEGEVILLE,PA,19426-4927,UNITED STATES,NaN,Allopathic & Osteopathic Physicians|Internal M...,PA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
37,Covered Recipient Physician,39,1003042169,JACQUELINE,Y,LONIER,NaN,JACQUELINE,YUEY,LONIER,NaN,1150 SAINT NICHOLAS AVE,NaN,NEW YORK,NY,10032-3822,UNITED STATES,NaN,Allopathic & Osteopathic Physicians|Internal M...,NY,NaN,NaN,NaN,NaN,NaN,NaN,JACKIE,LONIER,NaN,NaN,NaN,NaN,False
59,Covered Recipient Physician,64,1003081944,TONSLYN,A,TOURE,NaN,TONSLYN,NaN,TOURE,NaN,375 WAMPANOAG TRL STE 202B,NaN,RIVERSIDE,RI,02915,UNITED STATES,NaN,Allopathic & Osteopathic Physicians|Internal M...,MA,RI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
182,Covered Recipient Physician,196,1003832437,LAWRENCE,FAYEZ,NESHIWAT,NaN,NaN,NaN,NaN,NaN,944 N BROADWAY,SUITE 205,YONKERS,NY,10701-1304,UNITED STATES,NaN,Allopathic & Osteopathic Physicians|Internal M...,NY,CT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
193,Covered Recipient Physician,207,1003839101,THOMAS,M,FLOOD,NaN,NaN,NaN,NaN,NaN,5667 PEACHTREE DUNWOODY RD 290,NaN,ATLANTA,GA,30342-1714,UNITED STATES,NaN,Allopathic & Osteopathic Physicians|Internal M...,GA,MI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1313394,Covered Recipient Physician,11261124,1942650197,ASHLEY,NaN,JANCUSKA,NaN,ASHLEY,MARIE,JANCUSKA,NaN,8435 CLEARVISTA PL STE 101,NaN,INDIANAPOLIS,IN,46256-3761,UNITED STATES,NaN,Allopathic & Osteopathic Physicians|Internal M...,IN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1313489,Covered Recipient Physician,11261773,1417308685,ANNA MELISSA,SENGA,LO,NaN,NaN,NaN,NaN,NaN,1712 LILIHA ST STE 202,NaN,HONOLULU,HI,96817-5409,UNITED STATES,NaN,Allopathic & Osteopathic Physicians|Internal M...,HI,PA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1320481,Covered Recipient Physician,11304548,1346762606,SAIF,MUNTHER ZA'AL AL,BORGAN,NaN,NaN,NaN,NaN,NaN,CLEVELAND CLINIC 9500 EUCLID AVENUENA-23,NaN,CLEVELAND,OH,44195-7408,UNITED STATES,NaN,NaN,OH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1321766,Covered Recipient Physician,11305986,1427402551,KAVITHA,NaN,GANESAN,NaN,NaN,NaN,NaN,NaN,2001 KINGSLEY AVENUE,NaN,ORANGE PARK,FL,32073,UNITED STATES,NaN,NaN,FL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
1323400,Covered Recipient Physician,11307748,1306392675,LING,NaN,CUI,NaN,NaN,NaN,NaN,NaN,2209 MERRICK RD STE 101,NaN,MERRICK,NY,11566-4770,UNITED STATES,NaN,NaN,NY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False

In [ ]:
list_id = list(df_id["covered_recipient_profile_id"])

## save Profile dataset matching with NPI

In [ ]:
npi_specialty.to_csv(path_out_profile + "NPI physician profile data.csv", index=None)
df_id.to_csv(path_out_profile + "matched physician profile data.csv", index=None)

# Extract payment data and save payment dataset

## General payments

### extract payment data in 2013-2021

#### file name

In [ ]:
list_general2013 = glob.glob("/content/drive/MyDrive/OPD/2013/OP_DTL_GNRL_PGYR*.csv")
list_general2014 = glob.glob("/content/drive/MyDrive/OPD/2014/OP_DTL_GNRL_PGYR*.csv")
list_general2015 = glob.glob("/content/drive/MyDrive/OPD/2015/OP_DTL_GNRL_PGYR*.csv")
list_general2016 = glob.glob("/content/drive/MyDrive/OPD/2016/OP_DTL_GNRL_PGYR*.csv")
list_general2017 = glob.glob("/content/drive/MyDrive/OPD/2017/OP_DTL_GNRL_PGYR*.csv")
list_general2018 = glob.glob("/content/drive/MyDrive/OPD/2018/OP_DTL_GNRL_PGYR*.csv")
list_general2019 = glob.glob("/content/drive/MyDrive/OPD/2019/OP_DTL_GNRL_PGYR*.csv")
list_general2020 = glob.glob("/content/drive/MyDrive/OPD/2020/OP_DTL_GNRL_PGYR*.csv")
list_general2021 = glob.glob("/content/drive/MyDrive/OPD/2021/OP_DTL_GNRL_PGYR*.csv")

#### 2013 data

In [ ]:
df_pay13 = pd.read_csv(list_general2013[0], low_memory=False)
list_df_pay_columns13 = list(df_pay13.columns)
df_pay_id13g = pd.DataFrame(columns=list_df_pay_columns13)
df_pay_id13g

Empty DataFrame
Columns: [Change_Type, Covered_Recipient_Type, Teaching_Hospital_CCN, Teaching_Hospital_ID, Teaching_Hospital_Name, Physician_Profile_ID, Physician_First_Name, Physician_Middle_Name, Physician_Last_Name, Physician_Name_Suffix, Recipient_Primary_Business_Street_Address_Line1, Recipient_Primary_Business_Street_Address_Line2, Recipient_City, Recipient_State, Recipient_Zip_Code, Recipient_Country, Recipient_Province, Recipient_Postal_Code, Physician_Primary_Type, Physician_Specialty, Physician_License_State_code1, Physician_License_State_code2, Physician_License_State_code3, Physician_License_State_code4, Physician_License_State_code5, Submitting_Applicable_Manufacturer_or_Applicable_GPO_Name, Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_ID, Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Name, Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_State, Applicable_Manufacturer_or_Applicable_GPO_Making_Payment_Country, Total_Amount_of_Payment_USDollars, Date_of_Payment, Number_of_Payments_Included_in_Total_Amount, Form_of_Payment_or_Transfer_of_Value, Nature_of_Payment_or_Transfer_of_Value, City_of_Travel, State_of_Travel, Country_of_Travel, Physician_Ownership_Indicator, Third_Party_Payment_Recipient_Indicator, Name_of_Third_Party_Entity_Receiving_Payment_or_Transfer_of_Value, Charity_Indicator, Third_Party_Equals_Covered_Recipient_Indicator, Contextual_Information, Delay_in_Publication_Indicator, Record_ID, Dispute_Status_for_Publication, Product_Indicator, Name_of_Associated_Covered_Drug_or_Biological1, Name_of_Associated_Covered_Drug_or_Biological2, Name_of_Associated_Covered_Drug_or_Biological3, Name_of_Associated_Covered_Drug_or_Biological4, Name_of_Associated_Covered_Drug_or_Biological5, NDC_of_Associated_Covered_Drug_or_Biological1, NDC_of_Associated_Covered_Drug_or_Biological2, NDC_of_Associated_Covered_Drug_or_Biological3, NDC_of_Associated_Covered_Drug_or_Biological4, NDC_of_Associated_Covered_Drug_or_Biological5, Name_of_Associated_Covered_Device_or_Medical_Supply1, Name_of_Associated_Covered_Device_or_Medical_Supply2, Name_of_Associated_Covered_Device_or_Medical_Supply3, Name_of_Associated_Covered_Device_or_Medical_Supply4, Name_of_Associated_Covered_Device_or_Medical_Supply5, Program_Year, Payment_Publication_Date]
Index: []

#### 2014 data

In [ ]:
for path_data in list_general2013:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Physician_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id13g = pd.concat([df_pay_id13g, df_payg], axis=0)
del df_pay13

In [ ]:
df_pay14 = pd.read_csv(list_general2014[0], low_memory=False)
list_df_pay_columns14 = list(df_pay14.columns)
df_pay_id14g = pd.DataFrame(columns=list_df_pay_columns14)
df_pay_id14g

for path_data in list_general2014:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Physician_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id14g = pd.concat([df_pay_id14g, df_payg], axis=0)
del df_pay14

#### 2015 data

In [ ]:
df_pay15 = pd.read_csv(list_general2015[0], low_memory=False)
list_df_pay_columns15 = list(df_pay15.columns)
df_pay_id15g = pd.DataFrame(columns=list_df_pay_columns15)
df_pay_id15g

for path_data in list_general2015:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Physician_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id15g = pd.concat([df_pay_id15g, df_payg], axis=0)
del df_pay15
del list_df_pay_columns15

#### 2016

In [ ]:
df_pay16 = pd.read_csv(list_general2016[0], low_memory=False)
list_df_pay_columns16 = list(df_pay16.columns)
df_pay_id16g = pd.DataFrame(columns=list_df_pay_columns16)
df_pay_id16g

for path_data in list_general2016:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Covered_Recipient_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id16g = pd.concat([df_pay_id16g, df_payg], axis=0)
del df_pay16
del list_df_pay_columns16

#### 2017

In [ ]:
df_pay17 = pd.read_csv(list_general2017[0], low_memory=False)
list_df_pay_columns17 = list(df_pay17.columns)
df_pay_id17g = pd.DataFrame(columns=list_df_pay_columns17)
df_pay_id17g

for path_data in list_general2017:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Covered_Recipient_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id17g = pd.concat([df_pay_id17g, df_payg], axis=0)
del df_pay17
del list_df_pay_columns17

#### 2018

In [ ]:
df_pay18 = pd.read_csv(list_general2018[0], low_memory=False)
list_df_pay_columns18 = list(df_pay18.columns)
df_pay_id18g = pd.DataFrame(columns=list_df_pay_columns18)
df_pay_id18g

for path_data in list_general2018:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Covered_Recipient_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id18g = pd.concat([df_pay_id18g, df_payg], axis=0)
del df_pay18
del list_df_pay_columns18

#### 2019

In [ ]:
df_pay19 = pd.read_csv(list_general2019[0], low_memory=False)
list_df_pay_columns19 = list(df_pay19.columns)
df_pay_id19g = pd.DataFrame(columns=list_df_pay_columns19)
df_pay_id19g

for path_data in list_general2019:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Covered_Recipient_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id19g = pd.concat([df_pay_id19g, df_payg], axis=0)
del df_pay19
del list_df_pay_columns19

#### 2020

In [ ]:
df_pay20 = pd.read_csv(list_general2020[0], low_memory=False)
list_df_pay_columns20 = list(df_pay20.columns)
df_pay_id20g = pd.DataFrame(columns=list_df_pay_columns20)
df_pay_id20g

for path_data in list_general2020:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Covered_Recipient_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id20g = pd.concat([df_pay_id20g, df_payg], axis=0)
del df_pay20
del list_df_pay_columns20

#### 2021

In [ ]:
df_pay21 = pd.read_csv(list_general2021[0], low_memory=False)
list_df_pay_columns21 = list(df_pay21.columns)
df_pay_id21g = pd.DataFrame(columns=list_df_pay_columns21)
df_pay_id21g

for path_data in list_general2021:
    df_payg = pd.read_csv(path_data, low_memory=False)
    df_payg = df_payg[df_payg["Covered_Recipient_Profile_ID"].isin(list_id)]
    df_payg = df_payg.reset_index(drop=True)
    df_pay_id21g = pd.concat([df_pay_id21g, df_payg], axis=0)
del df_pay21
del list_df_pay_columns21

### combine dataset to one dataset

In [ ]:
df1315g = pd.concat([df_pay_id13g, df_pay_id14g, df_pay_id15g], axis = 0)

del df_pay_id13g
del df_pay_id14g
del df_pay_id15g

In [ ]:
df1315g= df1315g.rename(columns={"Physician_Profile_ID":"Covered_Recipient_Profile_ID"})
df1315g= df1315g.rename(columns={"Physician_First_Name":"Covered_Recipient_First_Name"})
df1315g= df1315g.rename(columns={"Physician_Middle_Name":"Covered_Recipient_Middle_Name"})
df1315g= df1315g.rename(columns={"Physician_Last_Name":"Covered_Recipient_Last_Name"})
df1315g= df1315g.rename(columns={"Physician_Name_Suffix":"Covered_Recipient_Name_Suffix"})
df1315g= df1315g.rename(columns={"Physician_Primary_Type":"Covered_Recipient_Primary_Type_1"})
df1315g= df1315g.rename(columns={"Physician_Specialty":"Covered_Recipient_Specialty_1"})
df1315g= df1315g.rename(columns={"Physician_License_State_code1" :"Covered_Recipient_License_State_code1"})
df1315g= df1315g.rename(columns={"Physician_License_State_code2" :"Covered_Recipient_License_State_code2"})
df1315g= df1315g.rename(columns={"Physician_License_State_code3" :"Covered_Recipient_License_State_code3"})
df1315g= df1315g.rename(columns={"Physician_License_State_code4" :"Covered_Recipient_License_State_code4"})
df1315g= df1315g.rename(columns={"Physician_License_State_code5" :"Covered_Recipient_License_State_code5"})

In [ ]:
df1315g= df1315g.rename(columns={"Product_Indicator":"Related_Product_Indicator"})
df1315g= df1315g.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological1":"Associated_Drug_or_Biological_NDC_1"})
df1315g= df1315g.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological2":"Associated_Drug_or_Biological_NDC_2"})
df1315g= df1315g.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological3":"Associated_Drug_or_Biological_NDC_3"})
df1315g= df1315g.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological4":"Associated_Drug_or_Biological_NDC_4"})
df1315g= df1315g.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological5":"Associated_Drug_or_Biological_NDC_5"})
df1315g= df1315g.rename(columns = {"Physician_NPI":"Covered_Recipient_NPI"})

In [ ]:
df1315g["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1"] = df1315g['Name_of_Associated_Covered_Drug_or_Biological1'].astype(str) 
+ df1315g["Name_of_Associated_Covered_Device_or_Medical_Supply1"]
df1315g["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2"] = df1315g['Name_of_Associated_Covered_Drug_or_Biological2'].astype(str) 
+ df1315g["Name_of_Associated_Covered_Device_or_Medical_Supply2"]
df1315g["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3"] = df1315g['Name_of_Associated_Covered_Drug_or_Biological3'].astype(str) 
+ df1315g["Name_of_Associated_Covered_Device_or_Medical_Supply3"]
df1315g["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4"] = df1315g['Name_of_Associated_Covered_Drug_or_Biological4'].astype(str) 
+ df1315g["Name_of_Associated_Covered_Device_or_Medical_Supply4"]
df1315g["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5"] = df1315g['Name_of_Associated_Covered_Drug_or_Biological5'].astype(str) 
+ df1315g["Name_of_Associated_Covered_Device_or_Medical_Supply5"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
22682    NaN
22683    NaN
22684    NaN
22685    NaN
22686    NaN
Name: Name_of_Associated_Covered_Device_or_Medical_Supply5, Length: 745235, dtype: object

In [ ]:
df1621g = pd.concat([df_pay_id16g, df_pay_id17g, 
                    df_pay_id18g, df_pay_id19g, 
                    df_pay_id20g, df_pay_id21g], axis = 0)
del df_pay_id16g
del df_pay_id17g
del df_pay_id18g
del df_pay_id19g
del df_pay_id20g
del df_pay_id21g

In [ ]:
dfg = pd.concat([df1315g,df1621g], axis = 0)

In [ ]:
del df1315g
del df1621g

In [ ]:
dfg = dfg.drop(["Name_of_Associated_Covered_Device_or_Medical_Supply1",
             "Name_of_Associated_Covered_Device_or_Medical_Supply2",
             "Name_of_Associated_Covered_Device_or_Medical_Supply3",
             "Name_of_Associated_Covered_Device_or_Medical_Supply4",
             "Name_of_Associated_Covered_Device_or_Medical_Supply5",
             "Name_of_Associated_Covered_Drug_or_Biological1", 
             "Name_of_Associated_Covered_Drug_or_Biological2", 
             "Name_of_Associated_Covered_Drug_or_Biological3", 
             "Name_of_Associated_Covered_Drug_or_Biological4", 
             "Name_of_Associated_Covered_Drug_or_Biological5"], 
             axis=1)
dfg=dfg.replace("nan", "")
dfg=dfg.replace("NaN", "")

In [ ]:
dfg.to_csv(path_out1 + "full_general payments dataset2013-2021.csv", index=None)

KeyboardInterrupt: ignored

In [ ]:
dfg

## Research payment

###extract payment data

In [ ]:
df_pay13r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR13_P012221/OP_DTL_RSRCH_PGYR2013_P01222021.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay13r = pd.concat((r for r in df_pay13r), ignore_index=True)

In [ ]:
df_pay_id13r = df_pay13r[df_pay13r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay13r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay13r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay13r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay13r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

#### 2014 payment data

In [ ]:
df_pay14r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR14_P012122/OP_DTL_RSRCH_PGYR2014_P01212022.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay14r = pd.concat((r for r in df_pay14r), ignore_index=True)

In [ ]:
df_pay_id14r = df_pay14r[df_pay14r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay14r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay14r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay14r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay14r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

#### 2015 payment data

In [ ]:
df_pay15r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR15_P063022/OP_DTL_RSRCH_PGYR2015_P06302022.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay15r = pd.concat((r for r in df_pay15r), ignore_index=True)

In [ ]:
df_pay_id15r = df_pay15r[df_pay15r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay15r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay15r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay15r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay15r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

#### 2016 payment data

In [ ]:
df_pay16r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR16_P063022/OP_DTL_RSRCH_PGYR2016_P06302022.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay16r = pd.concat((r for r in df_pay16r), ignore_index=True)

In [ ]:
df_pay_id16r = df_pay16r[df_pay16r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay16r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay16r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay16r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay16r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

#### 2017 payment data

In [ ]:
df_pay17r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR17_P063022/OP_DTL_RSRCH_PGYR2017_P06302022.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay17r = pd.concat((r for r in df_pay17r), ignore_index=True)

In [ ]:
df_pay_id17r = df_pay17r[df_pay17r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay17r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay17r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay17r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay17r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

#### 2018 payment data

In [ ]:
df_pay18r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR18_P063022/OP_DTL_RSRCH_PGYR2018_P06302022.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay18r = pd.concat((r for r in df_pay18r), ignore_index=True)

In [ ]:
df_pay_id18r = df_pay18r[df_pay18r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay18r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay18r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay18r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay18r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

#### 2019 payment data

In [ ]:
df_pay19r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR19_P063022/OP_DTL_RSRCH_PGYR2019_P06302022.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay19r = pd.concat((r for r in df_pay19r), ignore_index=True)

In [ ]:
df_pay_id19r = df_pay19r[df_pay19r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay19r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay19r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay19r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay19r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

#### 2020 payment data

In [ ]:
df_pay20r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR20_P063022/OP_DTL_RSRCH_PGYR2020_P06302022.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay20r = pd.concat((r for r in df_pay20r), ignore_index=True)

In [ ]:
df_pay_id20r = df_pay20r[df_pay20r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay20r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay20r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay20r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay20r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

#### 2021 payment data

In [ ]:
df_pay21r = pd.read_csv("/content/drive/MyDrive/OPD/PGYR21_P063022/OP_DTL_RSRCH_PGYR2021_P06302022.csv", 
                        low_memory=False, chunksize= 200000)

In [ ]:
df_pay21r = pd.concat((r for r in df_pay21r), ignore_index=True)

In [ ]:
df_pay_id21r = df_pay21r[df_pay21r["Principal_Investigator_1_Profile_ID"].isin(list_id) |
                      df_pay21r["Principal_Investigator_2_Profile_ID"].isin(list_id) |
                      df_pay21r["Principal_Investigator_3_Profile_ID"].isin(list_id) |
                      df_pay21r["Principal_Investigator_4_Profile_ID"].isin(list_id) |
                      df_pay21r["Principal_Investigator_5_Profile_ID"].isin(list_id) ]

### Rename columns

In [ ]:
del df_pay13r
del df_pay14r
del df_pay15r
del df_pay16r
del df_pay17r
del df_pay18r 
del df_pay19r
del df_pay20r
del df_pay21r

In [ ]:
df1315r = pd.concat([df_pay_id13r, df_pay_id14r, df_pay_id15r], axis = 0)

In [ ]:
df1315r= df1315r.rename(columns={"Physician_Profile_ID":"Covered_Recipient_Profile_ID"})
df1315r= df1315r.rename(columns={"Physician_First_Name":"Covered_Recipient_First_Name"})
df1315r= df1315r.rename(columns={"Physician_Middle_Name":"Covered_Recipient_Middle_Name"})
df1315r= df1315r.rename(columns={"Physician_Last_Name":"Covered_Recipient_Last_Name"})
df1315r= df1315r.rename(columns={"Physician_Name_Suffix":"Covered_Recipient_Name_Suffix"})
df1315r= df1315r.rename(columns={"Physician_Primary_Type":"Covered_Recipient_Primary_Type_1"})
df1315r= df1315r.rename(columns={"Physician_Specialty":"Covered_Recipient_Specialty_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_1_Primary_Type":"Principal_Investigator_1_Primary_Type_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_1_Specialty":"Principal_Investigator_1_Specialty_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_2_Primary_Type":"Principal_Investigator_2_Primary_Type_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_2_Specialty":"Principal_Investigator_2_Specialty_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_3_Primary_Type":"Principal_Investigator_3_Primary_Type_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_3_Specialty":"Principal_Investigator_3_Specialty_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_4_Primary_Type":"Principal_Investigator_4_Primary_Type_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_4_Specialty":"Principal_Investigator_4_Specialty_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_5_Primary_Type":"Principal_Investigator_5_Primary_Type_1"})
df1315r= df1315r.rename(columns={"Principal_Investigator_5_Specialty":"Principal_Investigator_5_Specialty_1"})

In [ ]:
df1315r= df1315r.rename(columns={"Physician_License_State_code1" :"Covered_Recipient_License_State_code1"})
df1315r= df1315r.rename(columns={"Physician_License_State_code2" :"Covered_Recipient_License_State_code2"})
df1315r= df1315r.rename(columns={"Physician_License_State_code3" :"Covered_Recipient_License_State_code3"})
df1315r= df1315r.rename(columns={"Physician_License_State_code4" :"Covered_Recipient_License_State_code4"})
df1315r= df1315r.rename(columns={"Physician_License_State_code5" :"Covered_Recipient_License_State_code5"})

df1315r= df1315r.rename(columns={"Product_Indicator":"Related_Product_Indicator"})
df1315r= df1315r.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological1":"Associated_Drug_or_Biological_NDC_1"})
df1315r= df1315r.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological2":"Associated_Drug_or_Biological_NDC_2"})
df1315r= df1315r.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological3":"Associated_Drug_or_Biological_NDC_3"})
df1315r= df1315r.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological4":"Associated_Drug_or_Biological_NDC_4"})
df1315r= df1315r.rename(columns={"NDC_of_Associated_Covered_Drug_or_Biological5":"Associated_Drug_or_Biological_NDC_5"})
df1315r= df1315r.rename(columns = {"Physician_NPI":"Covered_Recipient_Profile_NPI"})

df1315r["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_1"] = df1315r['Name_of_Associated_Covered_Drug_or_Biological1'].astype(str) 
+ df1315r["Name_of_Associated_Covered_Device_or_Medical_Supply1"]
df1315r["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_2"] = df1315r['Name_of_Associated_Covered_Drug_or_Biological2'].astype(str) 
+ df1315r["Name_of_Associated_Covered_Device_or_Medical_Supply2"]
df1315r["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_3"] = df1315r['Name_of_Associated_Covered_Drug_or_Biological3'].astype(str) 
+ df1315r["Name_of_Associated_Covered_Device_or_Medical_Supply3"]
df1315r["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_4"] = df1315r['Name_of_Associated_Covered_Drug_or_Biological4'].astype(str) 
+ df1315r["Name_of_Associated_Covered_Device_or_Medical_Supply4"]
df1315r["Name_of_Drug_or_Biological_or_Device_or_Medical_Supply_5"] = df1315r['Name_of_Associated_Covered_Drug_or_Biological5'].astype(str) 
+ df1315r["Name_of_Associated_Covered_Device_or_Medical_Supply5"]

In [ ]:
df1621r = pd.concat([df_pay_id16r, df_pay_id17r, 
                    df_pay_id18r, df_pay_id19r, 
                    df_pay_id20r, df_pay_id21r], axis = 0)

In [ ]:
dfr = pd.concat([df1315r, df1621r])

In [ ]:
dfr = dfr.drop(["Name_of_Associated_Covered_Device_or_Medical_Supply1",
             "Name_of_Associated_Covered_Device_or_Medical_Supply2",
             "Name_of_Associated_Covered_Device_or_Medical_Supply3",
             "Name_of_Associated_Covered_Device_or_Medical_Supply4",
             "Name_of_Associated_Covered_Device_or_Medical_Supply5",
             "Name_of_Associated_Covered_Drug_or_Biological1", 
             "Name_of_Associated_Covered_Drug_or_Biological2", 
             "Name_of_Associated_Covered_Drug_or_Biological3", 
             "Name_of_Associated_Covered_Drug_or_Biological4", 
             "Name_of_Associated_Covered_Drug_or_Biological5"], 
             axis=1)
dfr=dfr.replace("nan", "")
dfr=dfr.replace("NaN", "")

In [ ]:
dfr.to_csv(path_out2 + "full_research payments dataset2013-2021.csv", index=None)

In [ ]:
del df_pay_id13r
del df_pay_id14r
del df_pay_id15r
del df_pay_id16r
del df_pay_id17r
del df_pay_id18r
del df_pay_id19r
del df_pay_id20r
del df_pay_id21r

In [ ]:
del df1315r
del df1621r

## Ownership payments

In [ ]:
df_pay13o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR13_P012221/OP_DTL_OWNRSHP_PGYR2013_P01222021.csv", low_memory=False)
df_pay_id13o = df_pay13o[df_pay13o["Physician_Profile_ID"].isin(list_id)]

df_pay14o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR14_P012122/OP_DTL_OWNRSHP_PGYR2014_P01212022.csv", low_memory=False)
df_pay_id14o = df_pay14o[df_pay14o["Physician_Profile_ID"].isin(list_id)]

df_pay15o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR15_P063022/OP_DTL_OWNRSHP_PGYR2015_P06302022.csv", low_memory=False)
df_pay_id15o = df_pay15o[df_pay15o["Physician_Profile_ID"].isin(list_id)]

df_pay16o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR16_P063022/OP_DTL_OWNRSHP_PGYR2016_P06302022.csv", low_memory=False)
df_pay_id16o = df_pay16o[df_pay16o["Physician_Profile_ID"].isin(list_id)]

df_pay17o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR17_P063022/OP_DTL_OWNRSHP_PGYR2017_P06302022.csv", low_memory=False)
df_pay_id17o = df_pay17o[df_pay17o["Physician_Profile_ID"].isin(list_id)]

df_pay18o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR18_P063022/OP_DTL_OWNRSHP_PGYR2018_P06302022.csv", low_memory=False)
df_pay_id18o = df_pay18o[df_pay18o["Physician_Profile_ID"].isin(list_id)]

df_pay19o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR19_P063022/OP_DTL_OWNRSHP_PGYR2019_P06302022.csv", low_memory=False)
df_pay_id19o = df_pay19o[df_pay19o["Physician_Profile_ID"].isin(list_id)]

df_pay20o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR20_P063022/OP_DTL_OWNRSHP_PGYR2020_P06302022.csv", low_memory=False)
df_pay_id20o = df_pay20o[df_pay20o["Physician_Profile_ID"].isin(list_id)]

df_pay21o = pd.read_csv("/content/drive/MyDrive/OPD/PGYR21_P063022/OP_DTL_OWNRSHP_PGYR2021_P06302022.csv", low_memory=False)
df_pay_id21o = df_pay21o[df_pay21o["Physician_Profile_ID"].isin(list_id)]

### merge ownership interest

In [ ]:
dfo = pd.concat([df_pay_id13o, df_pay_id14o ,
                   df_pay_id15o, df_pay_id16o, 
                    df_pay_id17o, df_pay_id18o, 
                    df_pay_id19o, df_pay_id20o, 
                    df_pay_id21o], axis = 0)
dfo
dfo.to_csv(path_out3 + "ownership_interest2013-2021_extract.csv", index=None)

In [ ]:
del df_pay_id13o
del df_pay_id14o
del df_pay_id15o
del df_pay_id16o
del df_pay_id17o
del df_pay_id18o
del df_pay_id19o
del df_pay_id20o
del df_pay_id21o

## Create pivot tables by physician profile ID and payment categories for statistical analyses

### general payments pivot by physician profile ID

In [ ]:
df_general_pivot = dfg.pivot_table(index ='Covered_Recipient_Profile_ID', 
                                   columns = 'Program_Year', 
                                  values= 'Total_Amount_of_Payment_USDollars', 
                                   aggfunc = ['sum'] ).fillna(0)
df_general_pivot['id', 'covered_recipient_profile_id'] = df_general_pivot.index

df_general_pivot = df_general_pivot.reset_index(level=0, drop=True)
df_general_pivot.columns = df_general_pivot.columns.droplevel(0)
df_general_pivot = df_general_pivot.reset_index()
df_general_pivot.drop('index', axis=1, inplace=True)

df_general_pivot.rename(columns = {2013:'general2013', 
                                   2014:'general2014',
                                   2015:'general2015',
                                   2016:'general2016',
                                   2017:'general2017',
                                   2018:'general2018',
                                   2019:'general2019',
                                   2020:'general2020',
                                   2021:'general2021'}
                        , inplace = True)

df_general_pivot.index = df_general_pivot['covered_recipient_profile_id']
df_general_pivot.drop('covered_recipient_profile_id', axis=1, inplace=True)
df_general_pivot

Program_Year,general2013,general2014,general2015,general2016,general2017,general2018,general2019,general2020,general2021
covered_recipient_profile_id,,,,,,,,,
4.0,170.12,77.38,295.25,265.49,75.27,158.68,0.00,12.29,26.87
39.0,144.29,4354.38,47.32,22.43,0.00,0.00,140.22,0.00,0.00
64.0,120.59,443.61,1247.85,772.65,37.65,0.00,0.00,0.00,0.00
196.0,2751.44,3394.84,4018.80,4946.66,4374.20,4279.13,5166.89,1025.59,2455.94
207.0,13288.45,26061.42,32002.91,5556.34,936.98,15.96,143.58,0.00,238.51
...,...,...,...,...,...,...,...,...,...
11261124.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,222.67
11261773.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2042.44
11304548.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,107.25
11305986.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,17.86
11307748.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,17.40

#### save pivot table

In [ ]:
df_general_pivot["index"] = df_general_pivot.index
df_general_pivot.to_csv(path_out1 + "general_pivot2013-2021_extract.csv", index=None)

#### Combine pivot table with the NPI profile dataset

In [ ]:
df_id.index = df_id['covered_recipient_profile_id']
df_id2 = pd.concat([df_id[['covered_recipient_profile_type', 
                           'covered_recipient_npi', 
                           'covered_recipient_profile_primary_specialty', 
                           'has_multiple_ids']], df_general_pivot],
                        axis = 1)
df_id2

,covered_recipient_profile_type,covered_recipient_npi,covered_recipient_profile_primary_specialty,has_multiple_ids,general2013,general2014,general2015,general2016,general2017,general2018,general2019,general2020,general2021,index
covered_recipient_profile_id,,,,,,,,,,,,,,
4.0,Covered Recipient Physician,1003024811,Allopathic & Osteopathic Physicians|Internal M...,False,170.12,77.38,295.25,265.49,75.27,158.68,0.00,12.29,26.87,4.0
39.0,Covered Recipient Physician,1003042169,Allopathic & Osteopathic Physicians|Internal M...,False,144.29,4354.38,47.32,22.43,0.00,0.00,140.22,0.00,0.00,39.0
64.0,Covered Recipient Physician,1003081944,Allopathic & Osteopathic Physicians|Internal M...,False,120.59,443.61,1247.85,772.65,37.65,0.00,0.00,0.00,0.00,64.0
196.0,Covered Recipient Physician,1003832437,Allopathic & Osteopathic Physicians|Internal M...,False,2751.44,3394.84,4018.80,4946.66,4374.20,4279.13,5166.89,1025.59,2455.94,196.0
207.0,Covered Recipient Physician,1003839101,Allopathic & Osteopathic Physicians|Internal M...,False,13288.45,26061.42,32002.91,5556.34,936.98,15.96,143.58,0.00,238.51,207.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11261124.0,Covered Recipient Physician,1942650197,Allopathic & Osteopathic Physicians|Internal M...,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,222.67,11261124.0
11261773.0,Covered Recipient Physician,1417308685,Allopathic & Osteopathic Physicians|Internal M...,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2042.44,11261773.0
11304548.0,Covered Recipient Physician,1346762606,NaN,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,107.25,11304548.0
11305986.0,Covered Recipient Physician,1427402551,NaN,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,17.86,11305986.0
11307748.0,Covered Recipient Physician,1306392675,NaN,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,17.40,11307748.0

### research payments pivot by physician profile ID

In [ ]:
dfr['PI_count']= dfr[['Principal_Investigator_1_Profile_ID', 
           'Principal_Investigator_2_Profile_ID', 
           'Principal_Investigator_3_Profile_ID', 
           'Principal_Investigator_4_Profile_ID', 
           'Principal_Investigator_5_Profile_ID']].count(axis = 1)

In [ ]:
dfr['per_payment'] = round((dfr['Total_Amount_of_Payment_USDollars'] / dfr['PI_count']),2)
dfr['per_payment'].replace([np.inf, -np.inf], 0, inplace=True)
dfr['per_payment']

0          128.7
1           67.5
2         2500.0
3          447.7
4           84.0
           ...
275609    1005.0
275610       9.0
275611       5.3
275612      56.9
275613      30.0
Name: per_payment, Length: 275614, dtype: float64

In [ ]:
df_research_pivot1 = dfr.pivot_table(index ='Principal_Investigator_1_Profile_ID', 
                                   columns = 'Program_Year', 
                                  values= 'per_payment', 
                                   aggfunc = ['sum']).fillna(0)

df_research_pivot2 = dfr.pivot_table(index ='Principal_Investigator_2_Profile_ID', 
                                   columns = 'Program_Year', 
                                  values= 'per_payment', 
                                   aggfunc = ['sum'] ).fillna(0)

df_research_pivot3 = dfr.pivot_table(index ='Principal_Investigator_3_Profile_ID', 
                                   columns = 'Program_Year', 
                                  values= 'per_payment', 
                                   aggfunc = ['sum']).fillna(0)

df_research_pivot4 = dfr.pivot_table(index ='Principal_Investigator_4_Profile_ID', 
                                   columns = 'Program_Year', 
                                  values= 'per_payment', 
                                   aggfunc = ['sum']).fillna(0)

df_research_pivot5 = dfr.pivot_table(index ='Principal_Investigator_5_Profile_ID', 
                                   columns = 'Program_Year', 
                                  values= 'per_payment', 
                                   aggfunc =['sum']).fillna(0)

df_research_pivot = pd.concat([df_research_pivot1, 
                               df_research_pivot2, 
                               df_research_pivot3, 
                               df_research_pivot4, 
                               df_research_pivot5], axis = 0).fillna(0)
df_research_pivot['id', 'covered_recipient_profile_id'] = df_research_pivot.index      


df_research_pivot = df_research_pivot.reset_index(level=0, drop=True)
df_research_pivot.columns = df_research_pivot.columns.droplevel(0)
df_research_pivot = df_research_pivot.reset_index()
df_research_pivot.drop('index', axis=1, inplace=True)
df_research_pivot.columns
df_research_pivot.rename(columns = {2013:'research2013', 
                                   2014:'research2014',
                                   2015:'research2015',
                                   2016:'research2016',
                                   2017:'research2017',
                                   2018:'research2018',
                                   2019:'research2019',
                                   2020:'research2020',
                                   2021:'research2021'}, inplace = True)
df_research_pivot.sort_values('covered_recipient_profile_id')

Program_Year,research2013,research2014,research2015,research2016,research2017,research2018,research2019,research2020,research2021,covered_recipient_profile_id
0,0.00,0.00,307963.00,1613939.00,1305000.00,0.00,0.00,0.00,0.00,567.0
1,299212.46,335490.95,257090.70,576200.47,133671.41,169123.88,374939.84,710984.03,72043.39,940.0
1281,62.50,24524.56,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1794.0
2,16584.89,231941.27,260797.57,313128.85,641016.10,410864.22,288783.56,106686.91,60609.49,1794.0
3,0.00,219594.70,133672.55,46715.56,199508.93,175329.54,23890.84,6053.57,0.00,2671.0
...,...,...,...,...,...,...,...,...,...,...
1276,0.00,0.00,0.00,0.00,0.00,0.00,24000.00,16319.00,0.00,4216796.0
1277,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,3342.98,4219433.0
1278,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,10508.37,5691235.0
1279,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,20638.23,5698877.0
1280,0.00,0.00,0.00,0.00,0.00,0.00,0.00,190285.95,40846.24,8792522.0

In [ ]:
df_research_pivot2 = df_research_pivot.pivot_table(index ='covered_recipient_profile_id', 
                                                   values= ['research2013',
                                                            'research2014', 
                                                            'research2015', 
                                                            'research2016', 
                                                            'research2017', 
                                                            'research2018', 
                                                            'research2019', 
                                                            'research2020', 
                                                            'research2021'], 
                                                    aggfunc = ['sum'] ).fillna(0)

df_research_pivot2['id', 'covered_recipient_profile_id'] = df_research_pivot2.index

df_research_pivot2 = df_research_pivot2.reset_index(level=0, drop=True)
df_research_pivot2.columns = df_research_pivot2.columns.droplevel(0)
df_research_pivot2 = df_research_pivot2.reset_index()
df_research_pivot2.drop('index', axis=1, inplace=True)
df_research_pivot2.index = df_research_pivot2['covered_recipient_profile_id']

df_research_pivot2 = df_research_pivot2[df_research_pivot2["covered_recipient_profile_id"].isin(list_id)] 
df_research_pivot2.drop('covered_recipient_profile_id', axis=1, inplace=True)
df_research_pivot2

df_research_pivot2.to_csv(path_out2 + "pivot2013-2021_extract.csv", index=None)

df_id3 = pd.concat([df_id2, df_research_pivot2],
                        axis = 1).fillna(0)

In [ ]:
df_id3 = pd.concat([df_id2, df_research_pivot2],
                        axis = 1).fillna(0)

### Pivot table by physician profile ID for ownership payments

In [ ]:
df_ownership_pivot = dfo.pivot_table(index ='Physician_Profile_ID', 
                                   columns = 'Program_Year', 
                                  values= 'Total_Amount_Invested_USDollars', 
                                   aggfunc = ['sum']).fillna(0)
df_ownership_pivot["index"] = df_ownership_pivot.index

df_ownership_pivot['id', 'covered_recipient_profile_id'] = df_ownership_pivot.index

df_ownership_pivot = df_ownership_pivot.reset_index(level=0, drop=True)
df_ownership_pivot.columns = df_ownership_pivot.columns.droplevel(0)
df_ownership_pivot = df_ownership_pivot.reset_index()
df_ownership_pivot.drop('index', axis=1, inplace=True)

df_ownership_pivot.rename(columns = {2013:'ownership2013', 
                                   2014:'ownership2014',
                                   2015:'ownership2015',
                                   2016:'ownership2016',
                                   2017:'ownership2017',
                                   2018:'ownership2018',
                                   2019:'ownership2019',
                                   2020:'ownership2020',
                                   2021:'ownership2021'}
                        , inplace = True)
df_ownership_pivot.index =df_ownership_pivot['covered_recipient_profile_id']
df_ownership_pivot.drop('covered_recipient_profile_id', axis=1, inplace=True)

In [ ]:
df_ownership_pivot

Program_Year,ownership2013,ownership2014,ownership2015,ownership2016,ownership2017,ownership2018,ownership2019,ownership2020,ownership2021,
covered_recipient_profile_id,,,,,,,,,,
2777,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,2777
67861,2.84,2.17,2.17,2.17,0.00,0.0,0.0,0.0,0.0,67861
134322,1.20,1.20,1.20,1.20,0.00,0.0,0.0,0.0,0.0,134322
191630,0.00,0.00,0.00,0.00,0.00,0.0,0.0,116250.0,0.0,191630
204852,0.00,2.17,2.17,2.17,0.00,0.0,0.0,0.0,0.0,204852
227831,2.84,2.17,2.17,2.17,0.00,0.0,0.0,0.0,0.0,227831
246797,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,246797
251977,251066.00,255179.00,305179.00,305178.00,337153.06,0.0,0.0,0.0,0.0,251977
273589,0.00,2.17,2.17,2.17,0.00,0.0,0.0,0.0,0.0,273589
324225,0.00,2.17,2.17,2.17,0.00,0.0,0.0,0.0,0.0,324225
326577,100086.00,100086.00,50043.00,100086.00,100086.03,0.0,0.0,0.0,0.0,326577
527796,0.00,2.17,2.17,2.17,0.00,0.0,0.0,0.0,0.0,527796
1217711,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,1217711
1375341,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,1375341

### Save profile dataset

In [ ]:
df_id4 = pd.concat([df_id3, df_ownership_pivot],
                        axis = 1).fillna(0)
df_id4['OPD_ID']= df_id4.index
df_id4.index= df_id4['covered_recipient_npi']
npi_specialty.index= npi_specialty['NPI']

df_npi_merge = pd.concat([npi_specialty, df_id4],
                         axis = 1).fillna(0)
df_npi_merge

,NPI,Entity Type Code,Replacement NPI,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider Middle Name,Provider Other Organization Name,Provider Other Organization Name Type Code,Provider Other Last Name,Provider Other First Name,Provider Other Middle Name,Provider Business Practice Location Address City Name,Provider Business Practice Location Address State Name,Provider Enumeration Date,Last Update Date,NPI Deactivation Reason Code,NPI Deactivation Date,NPI Reactivation Date,Provider Gender Code,Authorized Official Title or Position,Healthcare Provider Taxonomy Code_1,Healthcare Provider Primary Taxonomy Switch_1,Healthcare Provider Taxonomy Code_2,Healthcare Provider Primary Taxonomy Switch_2,Healthcare Provider Taxonomy Code_3,Healthcare Provider Primary Taxonomy Switch_3,Healthcare Provider Taxonomy Code_4,Healthcare Provider Primary Taxonomy Switch_4,Healthcare Provider Taxonomy Code_5,Healthcare Provider Primary Taxonomy Switch_5,Healthcare Provider Taxonomy Code_6,Healthcare Provider Primary Taxonomy Switch_6,Healthcare Provider Taxonomy Code_7,Healthcare Provider Primary Taxonomy Switch_7,Healthcare Provider Taxonomy Code_8,Healthcare Provider Primary Taxonomy Switch_8,Healthcare Provider Taxonomy Code_9,Healthcare Provider Primary Taxonomy Switch_9,Healthcare Provider Taxonomy Code_10,Healthcare Provider Primary Taxonomy Switch_10,Healthcare Provider Taxonomy Code_11,Healthcare Provider Primary Taxonomy Switch_11,Healthcare Provider Taxonomy Code_12,Healthcare Provider Primary Taxonomy Switch_12,Healthcare Provider Taxonomy Code_13,Healthcare Provider Primary Taxonomy Switch_13,Healthcare Provider Taxonomy Code_14,Healthcare Provider Primary Taxonomy Switch_14,Healthcare Provider Taxonomy Code_15,Healthcare Provider Primary Taxonomy Switch_15,Certification Date,month,day,year,cmonth,covered_recipient_profile_type,covered_recipient_npi,covered_recipient_profile_primary_specialty,has_multiple_ids,general2013,general2014,general2015,general2016,general2017,general2018,general2019,general2020,general2021,index,research2013,research2014,research2015,research2016,research2017,research2018,research2019,research2020,research2021,ownership2013,ownership2014,ownership2015,ownership2016,ownership2017,ownership2018,ownership2019,ownership2020,ownership2021,,OPD_ID
1003002049,1003002049,1.0,0.0,0,SRINIVASAN,LAKSHMI,0,0,0.0,0,0,0,FREMONT,CA,09/24/2007,05/27/2020,0.0,0,0,F,0,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,05/27/2020,9,24,2007,93,Covered Recipient Physician,1.003002e+09,Allopathic & Osteopathic Physicians|Internal M...,False,57.00,0.00,37.25,45.92,0.00,13.04,0.00,20.61,0.00,1046622.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1046622.0
1003010943,1003010943,1.0,0.0,0,KOSHY,ANOOPA,A.,0,0.0,0,0,0,CHICAGO,IL,06/13/2007,05/10/2018,0.0,0,0,F,0,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,6,13,2007,90,Covered Recipient Physician,1.003011e+09,Allopathic & Osteopathic Physicians|Internal M...,False,0.00,0.00,25.20,0.00,0.00,0.00,79.86,0.00,501.80,1292351.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1292351.0
1003011800,1003011800,1.0,0.0,0,BLOMEIER,HERMAN,0,0,0.0,0,0,0,SKOKIE,IL,06/20/2007,02/10/2021,0.0,0,0,M,0,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,02/10/2021,6,20,2007,90,Covered Recipient Physician,1.003012e+09,Allopathic & Osteopathic Physicians|Internal M...,False,1151.12,2731.51,117.88,0.00,0.00,18.92,0.00,101.53,0.00,363237.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,363237.0
1003013673,1003013673,1.0,0.0,0,KRETCHMAN,ERICA,MICHELLE,0,0.0,WESTLEY,ERICA,MICHELLE,RICHMOND,IN,06/28/2007,07/08/2022,0.0,0,0,F,0,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,07/08/2022,6,28,2007,90,Covered Recipient Physician,1.003014e+09,Allopathic & Osteopathic Physicians|Internal M...,False,454.39,3674.31,7440.92,20482.52,34545.67,57622.12,56531.08,90933.38,121285.44,136033.0,0.0,0.0,0.0,0.0,0.0,0.0,4000.0,6490.00,5160.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,136033.0
1003014705,1003014705,1.0,0.0,0,JINDAL,ANKUR,0,0,0.0,0,0,0,HUNTSVILLE,AL,07/05/2007,04/03/2017,0.0,0,0,M,0,207R00000X,N,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,7,5,2007,91,Covered Recipient Physician,1.003015e+09,Allopathic & Osteopathic Physicians|Internal M...,False,90.84,0.00,560.59,19.38,234.48,530.62,742.76,392.94,403.88,90602.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90602.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992980619,1992980619,1.0,0.0,0,GO,CHRISTINA,GRACE,0,0.0,0,0,0,ARLINGTON,VA,12/31/2007,01/24/2014,0.0,0,0,F,0,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,31,2007,96,Covered Recipient Physician,1.992981e+09,Allopathic & Osteopathic Physicians|Internal M...,False,440.43,1584.34,1180.23,428.74,428.41,652.18,421.07,89.64,420.73,363145.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,363145.0
1992988935,1992988935,1.0,0.0,0,OMRY ORBACH,GAL,0,0,0.0,0,0,0,SEATTLE,WA,12/13/2007,07/15/2013,0.0,0,0,F,0,207RE0101X,Y,207RE0101X,N,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,12,13,2007,96,Covered Recipient Physician,1.992989e+09,Allopathic & Osteopathic Physicians|Internal M...,False,40.55,0.00,160.65,0.00,0.00,0.00,0.00,0.00,0.00,181448.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,181448.0
1992992895,1992992895,1.0,0.0,0,HAWKINS,KARA,BRENN,0,0.0,0,0,0,CHARLOTTESVILLE,VA,09/25/2007,07/03/2018,0.0,0,0,F,0,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,9,25,2007,93,Covered Recipient Physician,1.992993e+09,Allopathic & Osteopathic Physicians|Internal M...,False,10.92,0.00,104.91,156.42,256.04,977.81,336.64,6125.69,2040.00,363158.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,363158.0
1992996375,1992996375,1.0,0.0,0,CHONGKRAIRATANAKUL,NATSURANG,0,0,0.0,0,0,0,ESCONDIDO,CA,08/09/2007,04/16/2021,0.0,0,0,F,0,207R00000X,N,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,04/16/2021,8,9,2007,92,Covered Recipient Physician,1.992996e+09,Allopathic & Osteopathic Physicians|Internal M...,False,190.16,1590.14,659.30,575.34,252.11,23.54,309.33,69.81,0.00,45154.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45154.0
1992997332,1992997332,1.0,0.0,0,ROTH,MARA,Y,0,0.0,0,0,0,SEATTLE,WA,08/09/2007,12/24/2012,0.0,0,0,F,0,207RE0101X,Y,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,9,2007,92,Covered Recipient Physician,1.992997e+09,Allopathic & Osteopathic Physicians|Internal M...,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,157211.82,19852.62,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,391530.0

In [1]:
df_npi_merge.to_csv(path_out_stata + "npi_dataset_payment2013-2021.csv", index=None)

NameError: ignored

In [ ]:
df_id4

,covered_recipient_profile_type,covered_recipient_npi,covered_recipient_profile_primary_specialty,has_multiple_ids,general2013,general2014,general2015,general2016,general2017,general2018,general2019,general2020,general2021,index,research2013,research2014,research2015,research2016,research2017,research2018,research2019,research2020,research2021,ownership2013,ownership2014,ownership2015,ownership2016,ownership2017,ownership2018,ownership2019,ownership2020,ownership2021,,OPD_ID
covered_recipient_npi,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1003024811,Covered Recipient Physician,1003024811,Allopathic & Osteopathic Physicians|Internal M...,False,170.12,77.38,295.25,265.49,75.27,158.68,0.00,12.29,26.87,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
1003042169,Covered Recipient Physician,1003042169,Allopathic & Osteopathic Physicians|Internal M...,False,144.29,4354.38,47.32,22.43,0.00,0.00,140.22,0.00,0.00,39.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39.0
1003081944,Covered Recipient Physician,1003081944,Allopathic & Osteopathic Physicians|Internal M...,False,120.59,443.61,1247.85,772.65,37.65,0.00,0.00,0.00,0.00,64.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64.0
1003832437,Covered Recipient Physician,1003832437,Allopathic & Osteopathic Physicians|Internal M...,False,2751.44,3394.84,4018.80,4946.66,4374.20,4279.13,5166.89,1025.59,2455.94,196.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,196.0
1003839101,Covered Recipient Physician,1003839101,Allopathic & Osteopathic Physicians|Internal M...,False,13288.45,26061.42,32002.91,5556.34,936.98,15.96,143.58,0.00,238.51,207.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,207.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1942650197,Covered Recipient Physician,1942650197,Allopathic & Osteopathic Physicians|Internal M...,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,222.67,11261124.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11261124.0
1417308685,Covered Recipient Physician,1417308685,Allopathic & Osteopathic Physicians|Internal M...,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,2042.44,11261773.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11261773.0
1346762606,Covered Recipient Physician,1346762606,0,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,107.25,11304548.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11304548.0
1427402551,Covered Recipient Physician,1427402551,0,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,17.86,11305986.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11305986.0
1306392675,Covered Recipient Physician,1306392675,0,False,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,17.40,11307748.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11307748.0